### PR TITLE
CMake: find_dependency(adiak) if Adiak used

### PR DESCRIPTION
**Pull request by ibaned**

### CODE REVIEW

**Comment by ibaned** [comment]
Without this, downstream users of `caliper` have to do both `find_package(adiak)` and `find_package(caliper)`. After this change, `find_package(caliper)` does everything.

**Comment by daboehme** [comment]
Hm, downstream codes don't have to use Adiak with Caliper. I wouldn't want to add the additional dependency on Adiak on codes that don't need it.

**Comment by ibaned** [comment]
> Hm, downstream codes don't have to use Adiak with Caliper. I wouldn't want to add the additional dependency on Adiak on codes that don't need it.

Yes, that's why I protected the `find_dependency` call with
```cmake
if (@CALIPER_HAVE_ADIAK@)
```
That way downstream codes don't try to bring in Adiak unless Caliper was explicitly compiled with it. When someone compiles Caliper with Adiak support, the exported CMake target `caliper` depends on `adiak::adiak` so this is necessary if Caliper has Adiak support.

Does this make sense or is there still a scenario in which I'm adding unnecessary dependence?

**Comment by ibaned** [comment]
Yes, but the `caliper` target still links to `adiak::adiak` no matter what so I don't see how downstream code could link to Caliper using CMake without doing `find_package(adiak)`, even if they don't plan to use the Adiak service.

Do you have an example of how I can install Caliper with Adiak support and still link to it via CMake without doing `find_package(adiak)`? Because that's all I'm trying to do.

**Comment by ibaned** [comment]
Is there any resolution on this? It still seems necessary to me for downstream users via CMake.

**Comment by daboehme** [comment]
Hi @ibaned , sorry for the delay, I had to look into this issue a bit closer. But you're right, we do indeed need the Adiak dependency propagated explicitly if Caliper is built statically.

There is the downside that now you have to explicitly provide the Adiak dependency to any downstream code even if Caliper is a dynamic library, which was just working before. Oh well.

**Comment by ibaned** [comment]
Thanks @daboehme ! Sorry for the repeated pinging on this.

**Pull request merged**
