### PR TITLE
Added in Variant constructors from a size_t and a const char*. 

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
Also added in C code for making a variant from a C string.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Weird, this isn't failing locally. I'll look into it

**Comment by DavidPoliakoff** [comment]
So this fails locally if we don't include the size_t overload, and fails on Travis when we don't include that overload

**Comment by jrmadsen** [comment]
If size_t is uint64_t, this will create duplicate overloads.

**Comment by DavidPoliakoff** [comment]
@jrmadsen : yeah, I have a solution, I just am on a network where I can't push. Basically I remake enable_if in 98 and only make the size_t overload if size_t and the other are distinguishable

**Comment by daboehme** [comment]
Hm, this captures more than it should. See added unit test. I don't think this is conceptually easy to solve ...

**Comment by DavidPoliakoff** [comment]
It'll probably be tomorrow before I can play with this, but thanks for the unit test, really good catch (I'm busy trying out the IO service)

**Comment by DavidPoliakoff** [comment]
Also, I _can_ go back to faffing around with differentiating that set of int'y things, but if possible I'd like to just make it right.

**Comment by daboehme** [comment]
Can't we just use `std::is_unsigned` (https://en.cppreference.com/w/cpp/types/is_unsigned)?

**Comment by DavidPoliakoff** [comment]
`Since C++11`? Can we can we?

**Comment by daboehme** [comment]
Yeah I guess. Turns out we've been using `std::map` and `std::string` (in Variant) from the annotation class for a while, and they are ABI incompatible between 98 and 11. So that would have been a disaster anyway. I guess C++98 people can use the C API.

**Comment by DavidPoliakoff** [comment]
@daboehme , if we're going that far, I'd like to really use 11, and type_traits. I don't think you want to be in the business of maintaining a slightly dumbed down version of std::enable_if and such

**Comment by daboehme** [comment]
@DavidPoliakoff, yeah, the type traits are much cleaner. The C++98 compatibility was a concern when we started, but it's half a decade later now and people should have moved on. Let's not tell Matt about this, though :)

Did some cleanup, let me know what you think.

**Comment by DavidPoliakoff** [comment]
@daboehme : looks solid, thanks for the last push. Also your secret is safe with me. Honestly, I think Matt might like where this winds up, I think we could have a C++'y traits'y Variant.h implementation backstopped by a set of C overloads, which could be a rather nice design

**Comment by DavidPoliakoff** [comment]
Also I just though "wait, Caliper can't be five years old" and then realized "wait, I've been working on it for over three years." Oh well

**Pull request merged**
