### PR TITLE
Fixed "is not" with literal python warnings

### PR DESCRIPTION
**Pull request by jrmadsen**
- So, my IDE reports these warnings as errors when `gen_services_inc.py` runs so I just tweaked it to suppress them 
  - in python, simply doing `if <string>` is the same as `if <string> != ""`
- Also, fixed a warning in Spot that popped up with a `for(const auto itr : <range>)` when it should be `for(const auto& itr : <range>)`
- Also, noticed this for the `-Wall` flag: `$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>,$<CXX_COMPILER_ID:GNU>>:-Wall>` and since it was used privately and thus doesn't need a generator expression, I just dropped in a `check_cxx_compiler_flag` (which I have found to be _super_ useful in dealing with all these different compilers)

### CODE REVIEW

**Comment by jrmadsen** [comment]
By the way, the warning/error I kept getting was:

```console
gen_services_inc.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
```

**Comment by daboehme** [comment]
Thanks @jrmadsen ! That python script is a bit of a hack and no one has looked into that for a while. I didn't know about `check_cxx_compiler_flag` - that's way better than the generator expression. It's used in a couple more places in the code so I'll move that to the top-level CMake script.

**Comment by jrmadsen** [comment]
No problem. Yeah generator expressions are great for some things (especially the `$<COMPILE_LANGUAGE:...>` ones) but god that syntax is awful. When we hosted a CMake tutorial at NERSC, the kitware people actually mentioned at one point that if they had realized how useful generator expressions would be when they first created them, they would have definitely created a better syntax.

Feel free to copy/paste/tweak the macro functions I've [created ~here](https://github.com/NERSC/timemory/blob/79f5f3b0ccb2485bbc9792f42fce116b52728760/cmake/Modules/Compilers.cmake#L235), I pretty much just do things like this now and basically don't worry about which flag goes with which compiler anymore:

```cmake
if(TIMEMORY_BUILD_QUIET)
    add_flag_if_avail(
        "-Wno-unused-value"
        "-Wno-unused-function"
        "-Wno-unknown-pragmas"
        "-Wno-deprecated-declarations"
        "-Wno-implicit-fallthrough"
        "-Wno-unused-command-line-argument")
endif()

# non-debug optimizations
#
if(NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND TIMEMORY_BUILD_EXTRA_OPTIMIZATIONS)
    add_flag_if_avail(
        "-finline-functions"
        "-funroll-loops"
        "-ftree-vectorize"
        "-ftree-loop-optimize"
        "-ftree-loop-vectorize"
        "-fno-signaling-nans"
        "-fno-trapping-math"
        "-fno-signed-zeros"
        "-ffinite-math-only"
        "-fno-math-errno"
        "-fpredictive-commoning"
        "-fvariable-expansion-in-unroller")
endif()
```

**Comment by DavidPoliakoff** [comment]
That script is a garbage hack

-the original author of said hack

**Pull request merged**
