### PR TITLE
[WIP] Missing changes for RADIUSS Spack Configs update

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR completes the work started in #582.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@daboehme The cce jobs (18.0.0 and 17.0.1) are failing because
```
error while loading shared libraries: libamdhip64.so.6: cannot open shared object file: No such file or directory
```
Why would those non-hip jobs depend on a hip library ?

**Comment by daboehme** [comment]
> @daboehme The cce jobs (18.0.0 and 17.0.1) are failing because
> 
> ```
> error while loading shared libraries: libamdhip64.so.6: cannot open shared object file: No such file or directory
> ```
> 
> Why would those non-hip jobs depend on a hip library ?

Hi @adrienbernede, that's a really good question. If Caliper is configured with `-DWITH_ROCTRACER=On` or `-DWITH_ROCM=On` it would pull in a `libamdhip64.so` dependency, but from the CMake output it looks like these flags are off. I don't know where it's coming from. Maybe `/opt/cray/pe/mpich/8.1.30/gtl/lib/libmpi_gtl_hsa.so` from MPI? Just speculation though. I'm not running into this when I try it manually. What's the CMake initial cache file that you use to configure Caliper?

**Comment by adrienbernede** [comment]
@daboehme it appears that the CI is not running on merge commits. That may due to a filter at mirror time.

**Comment by adrienbernede** [comment]
Superseded by #593

**Pull request closed without merging**
