### PR TITLE
Add histograms to aggregation

### PR DESCRIPTION
**Pull request by rblake-llnl**
Here is a patch to add histograms to the Aggregation API.  By default, it creates/reports a histogram distribution with logarithmic bins, each 4x bigger than the previous bin.  

This aggregation is useful for trying to diagnose any event that has a wide variation in allowed values.  

bin9 has entries in the range [floor{log_4(max)}, max]
bin0 has entries in the range (0, floor{log_4(max/65536)})

### CODE REVIEW

**Comment by daboehme** [comment]
Ok, once all the compile bugs are fixed something is still wrong with the shift operation. I'm getting invalid array accesses in AggregationDB.cpp:80. @rblake-llnl , can you look into this?

**Comment by rblake-llnl** [comment]
Had my max/min confused.  I think it works now?

**Comment by daboehme** [comment]
Was running a quick lulesh experiment and somehow everything ends up in bin 9, even when there is significant spread between values.

**Comment by rblake-llnl** [comment]
exponent extraction was broken, fixed?

**Comment by daboehme** [comment]
Yeah that looks better! I'll make it a compile-time option and add it in later today.

**Pull request merged**
